config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  resources :chuck_norris_facts, :defaults => { :format => 'json' }

  get "/chuck_dashboards", to: "chuck_dashboards#index"

  root "chuck_dashboards#index"

  namespace "api" do
    get "auto_savings", to: "auto_savings#index"
    post "auto_savings", to: "auto_savings#create"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
# == Schema Information
#
# Table name: bank_accounts
#
#  id           :integer          not null, primary key
#  account_type :string
#  balance      :float
#  customer_id  :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

# rubocop:disable all

class BankAccount < ActiveRecord::Base
  belongs_to :customer

  TYPES = %w(checking savings).freeze
  validates :account_type, inclusion: { in: TYPES }

  MIN_BALANCE = 10000.00 #all users are rich
  SAVINGS_PERCENT = 0.025
end

app/models/chuck_norris_fact.rb
# == Schema Information
#
# Table name: chuck_norris_facts
#
#  id          :integer          not null, primary key
#  fact        :string
#  karatepower :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class ChuckNorrisFact < ActiveRecord::Base
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  fname      :string
#  lname      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Customer < ActiveRecord::Base
  has_many :bank_accounts

  instance_eval do
    BankAccount::TYPES.each do |type|
      define_method "#{type}_account" do
        bank_accounts.where(account_type: type).first
      end
    end
  end

  def transfer_to_savings!
  end

  def can_auto_save?
    checking_account.has_minimum_balance?
  end
end

app/controllers/api/auto_savings_controller.rb
# rubocop:disable all
class Api::AutoSavingsController < ApplicationController
  def index
    render json: { message: "hello!" }, status: 200
  end

  def create
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chuck_dashboards_controller.rb
class ChuckDashboardsController < ApplicationController
  # GET /chuck_dashboards
  def index
  end
end

app/controllers/chuck_norris_facts_controller.rb
class ChuckNorrisFactsController < ApplicationController
  def index
    @facts = ChuckNorrisFact.all
    render json: @facts
  end
end

app/helpers/api/auto_saving_helper.rb
module Api::AutoSavingHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/chuck_dashboards_helper.rb
module ChuckDashboardsHelper
end

app/helpers/chuck_norris_facts_helper.rb
module ChuckNorrisFactsHelper
end

app/views/chuck_dashboards/_form.html.slim
= form_for @chuck_dashboard do |f|
  - if @chuck_dashboard.errors.any?
    #error_explanation
      h2 = "#{pluralize(@chuck_dashboard.errors.count, "error")} prohibited this chuck_dashboard from being saved:"
      ul
        - @chuck_dashboard.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/chuck_dashboards/edit.html.slim
h1 Editing chuck_dashboard

== render 'form'

= link_to 'Show', @chuck_dashboard
'  |
= link_to 'Back', chuck_dashboards_path

app/views/chuck_dashboards/index.html.erb
<div class="content">
  <p>
    Chuck has an JSON API like no other at:
    <a href="/chuck_norris_facts">Chuck Norris Fact API</a>
  </p>
</div>

app/views/chuck_dashboards/index.html.slim
.content
  p
    Chuck has an JSON API like no other at:
    a href="/chuck_norris_facts" Chuck Norris Fact API

app/views/chuck_dashboards/new.html.slim
h1 New chuck_dashboard

== render 'form'

= link_to 'Back', chuck_dashboards_path

app/views/chuck_dashboards/show.html.slim
p#notice = notice


= link_to 'Edit', edit_chuck_dashboard_path(@chuck_dashboard)
'  |
= link_to 'Back', chuck_dashboards_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrimeRevenue | Derailed</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <h1>Chuck's Dashboard</h1>
      <img class="chuck_image"/>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Derailed
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    .container
      h1 Chuck's DashBoard
      img.chuck_image
      = yield